apiVersion: v1
kind: Service
metadata:
  name: kato-opa
  labels:
    component: opa
spec:
  type: ClusterIP
  selector:
    component: opa
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http