name: Generate API from .proto
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Genereate code for kato api
      uses: brainyard-io/protoc-actions@master
      with:
        path: -I ./ api/kato.proto --go_out=plugins=grpc:./
    - name: push to repo
      uses: ludeeus/action-push@0.0.1
