name: kato_docker_ci
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]
 schedule:
   - cron: '0 1 * * *' # Daily at 01:00
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: get_version
     run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA})

   - name: Publish barinyard/kato:${{ env.RELEASE_VERSION }}
     uses: elgohr/Publish-Docker-Github-Action@master
     with:
       name: brainyard/kato
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       dockerfile: Dockerfile
       context: ./
       tags: "latest,${{ env.RELEASE_VERSION }}"
       
   - name: codecov
     run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
